totalballs = 3
maxplayers = 4
timedmode = false
bossybonusfromgoal = true
balltimeseconds = 9
warmupperiodtimeseconds = 9
loglevel = "debug"
keepalivems = 500

[goalie]
    start_position = 30
    center_position = 130
    backoff_degrees = 5
    limit_left = 170
    limit_right = 30
    target_g = 170
    target_o = 150
    target_a = 60
    target_l = 30
    device_address = "/dev/i2c-1"
    pulse_min = 500
    pulse_max = 2500
    arc_range = 180