totalballs = 3
maxplayers = 4
timedmode = false
bossybonusfromgoal = true
balltimeseconds = 9
warmupperiodtimeseconds = 9
loglevel = "debug"
keepalivems = 500
consolemode = true

[goalie]
    left_position = 180
    right_position = 0
    center_position = 80
    device_address = "/dev/i2c-1"
    pulse_min = 500
    pulse_max = 2500
    arc_range = 200
